# Generated by Django 4.2.4 on 2023-09-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracovnipozice',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
