# Generated by Django 4.2.5 on 2023-09-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0003_alter_firma_email_alter_firma_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracovnipozice',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workplace_web.firma'),
        ),
    ]
