# Generated by Django 4.2.5 on 2023-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0004_alter_pracovnipozice_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracovnipozice',
            name='mzda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
