# Generated by Django 4.2.4 on 2023-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0005_alter_pracovnipozice_mzda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracovnipozice',
            name='misto_prace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
