# Generated by Django 4.2.5 on 2023-11-03 11:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0008_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracovnipozice',
            name='popis',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
