# Generated by Django 4.2.4 on 2023-11-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0009_alter_pracovnipozice_popis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='editor_text',
        ),
    ]
