# Generated by Django 4.2.4 on 2023-11-03 19:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0010_rename_mymodel_editor_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PracovniKategorie',
        ),
        migrations.AlterField(
            model_name='firma',
            name='popis',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
