# Generated by Django 4.2.4 on 2023-11-04 14:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0012_alter_firma_popis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='popis',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
    ]
