# Generated by Django 4.2.5 on 2023-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0013_alter_firma_popis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='popis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
