# Generated by Django 4.2.5 on 2023-11-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0014_alter_firma_popis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
