# Generated by Django 4.2.4 on 2023-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0015_alter_firma_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='popis_firma',
            field=models.TextField(blank=True, null=True),
        ),
    ]
