# Generated by Django 4.2.4 on 2023-11-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0017_remove_firma_popis_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
