# Generated by Django 4.2.4 on 2023-11-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_web', '0018_firma_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='test',
        ),
    ]
